# basic setting
is_train: True
worker: 8

max_num: 40
inst_size: 64

# train
# basic
batch_size: 90
shuffle: true
max_epoch: 500
epoch_start: 1      # the starting epoch count

# optimizer
beta1: 0.5
beta2: 0.999
weight_decay: 0.0001
# lr
lr: 0.0002
lr_policy: 'linear'
# linear
epoch_init_lr: 500  # of epochs at starting learning rate'
niter_decay: 1500    # of epochs to linearly decay learning rate to zero
# step
step_size: 50
gamma: 0.5

# print
visual_img_freq: 8000
print_loss_freq: 1000
save_epoch_freq: 20

# test
test_batch_size: 1   # must be one
results_root: 'results/'
test_freq: 20

# dataset
dataset_dir: ''  # path to object dataset
input_nc: 3
mask_nc: 1
output_nc: 3
crop_size: 256
crop: True
flip: True

# net
use_dropout: False

# generator
ngf: 32
G_norm_type: in
ori_size: 16

# discriminator
ndf: 64
n_layers_D: 3
D_norm_type: batch
gan_mode: hinge
num_D: 3

# style encoder
nef: 64
downs_num: 3
style_dim: 256
E_norm_type: bn

# loss
no_ganFeat_loss: False
no_vgg_loss: False
lambda_L1: 10
lambda_feat: 10
lambda_vgg: 10
lambda_gan: 1